name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # her gün güncellenir
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake game
        uses: Platane/snk@v3
        with:
          github_user_name: ibrahimturkoz
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg

      - name: Push snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "generate snake"
          add: "dist/*"
